[package]
name = "username_checker"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true

[dependencies]
reqwest = {version = "0.12.7", features = ["blocking"]}
serde = "1.0.210"
serde_derive = "1.0.210"
toml = "0.8.19"
win32console = "0.1.2"


